### PR TITLE
Remove `testDebugUnitTest` from the dependencies of the `simulator` task

### LINKED ISSUE #10412: Gradle simulate task should not run tests
### Description

When running `./gradlew simulate` task, it should not run the `testDebugUnitTest` tests.

### Steps to Reproduce
Run `./gradlew simulate`, and tests will be run the first time.

I haven't had time to track this down, just wanted to file an issue.

### PR DESCRIPTION
**Pull request by MGaetan89**
This commit removes the dependency on the test task when running the `simulator` task.
We only need the `assembleDebug` task, to have an APK to run in the simulator.

Fixes #10412

### CODE REVIEW

File: simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt [hunk 1]
```diff
@@ -87,7 +86,7 @@ class SimulatorPlugin : Plugin<Project> {
       jvmArgs = testTask.jvmArgs + robolectricJvmArgs
       mainClass.set(MAIN_CLASS)
       args = listOf(resourceApkFile.absolutePath)
-      dependsOn(testTaskName, "assembleDebug")
+      dependsOn("assembleDebug")
```
Comment (utzcoz) [inline simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: IIUC, this simulate task requires `debutTest` task finished?

Comment (MGaetan89) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: Exactly, but according to the issue #10412 opened by @hoisie, it is not necessary to do see.
We just need an APK to install in the simulator.

Comment (utzcoz) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: What I know is that "apk" in test environment is liek "xxx._ap", and it is generated by test task. If you we remove this task dependency, how can we ensure the "apk" file is generated ?

Comment (MGaetan89) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: Ah, I thought it was looking for the app APK, not the test APK.

So maybe, `dependsOn` should include the following. What do you think?
https://github.com/robolectric/robolectric/blob/7a3b64d574dcd92bddd29e031296b8ca8e86be07/simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt#L45-L46

`dependsOn(targetTask, "assembleDebug"`

Comment (MGaetan89) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: I tried to run the `packageDebugUnitTestForUnitTest` locally, but it was not found (using AGP 8.10.1). Maybe we need to find a better way to generate the `apk-for-local-test.ap_` file (as suggested in #10382, suggestion 7)?

Comment (hoisie) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: Does the `assembleUnitTest` task work for you?

Comment (MGaetan89) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: The task exists, but it doesn't seem to generate the necessary file. I'm looking to see if I can find an other one

Comment (MGaetan89) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: My bad, the issue was that I didn't set `unitTests.isIncludeAndroidResources = true`.
I'll add a tip [here](https://github.com/robolectric/robolectric/blob/7a3b64d574dcd92bddd29e031296b8ca8e86be07/simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt#L46) if the task is not found.

Comment (hoisie) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: FWIW I just upgraded to AGP 8.10.1 and the task `packageDebugUnitTestForUnitTest` exists for me in a very simple project.

Comment (hoisie) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: @MGaetan89 that sounds great, thanks. We should also consider failing Robolectric tests if the ap_ is not supplied as well, but that can be a separate thing.

Comment (MGaetan89) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: @hoisie I've pushed the changes. Can you try again?

The build is already failed when the `.ap_` is not find:
https://github.com/robolectric/robolectric/blob/7a3b64d574dcd92bddd29e031296b8ca8e86be07/simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt#L47-L51

Or do you have something else in mind?

Comment (hoisie) [reply simulator-gradle-plugin/src/main/kotlin/org/robolectric/simulator/gradle/SimulatorPlugin.kt]: Yeah I was thinking that RobolectricTestRunner could check for the ap_ file to be supplied, to force people to set `unitTests.isIncludeAndroidResources = true` for tests as well (not just the simulator). But that can be a separate issue.

**Comment by hoisie** [comment]
Thank you @MGaetan89 for quickly resolving this issue, I'll CP these fixes and push out 4.15.
