### PR TITLE
fix: Avoid referring to Android S's TelephonyCallback

### LINKED ISSUE #7665: android.telephony.TelephonyCallback not found when running Robolectric 4.8+ with compileSdk less than 31
### Description

If we run tests with Robolectric 4.8+, and tests use `TelephonyManager` and project's compileSdk is less than 31.

### Steps to Reproduce

See https://github.com/firebase/firebase-android-sdk/blob/40df7c8ce70a2e97ac33fa73c12f956ff325ad85/transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java.

### Robolectric & Android Version

Robolectric 4.8+(I only test Robolectric 4.9, but https://github.com/robolectric/robolectric/commit/a48e30bcf13ae793bb5b195e56eefc8790b90eba is released from Robolectric 4.8, so this error might starts from 4.8+).

### Link to a public git repo demonstrating the problem:

https://github.com/robolectric/robolectric/commit/a48e30bcf13ae793bb5b195e56eefc8790b90eba.

### PR DESCRIPTION
**Pull request by styluo**
### Overview
fix #7665 
add test #7666 

compatibility problem like #5835
Avoid referring to Android S's TelephonyCallback
On some JVMs when running with SDK < 31
```
resources.arsc in APK '/Users/.m2/repository/org/robolectric/android-all-instrumented/11-robolectric-6757853-i4/android-all-instrumented-11-robolectric-6757853-i4.jar' is compressed.
Exception in thread "TrackMainThread" java.lang.NoClassDefFoundError: android/telephony/TelephonyCallback
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodDeclaredOnClass(ShadowWrangler.java:385)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:354)
	at org.robolectric.internal.bytecode.ShadowWrangler.pickShadowMethod(ShadowWrangler.java:331)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:190)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.telephony.TelephonyManager.<clinit>(TelephonyManager.java)
	at android.telephony.TelephonyFrameworkInitializer.lambda$registerServiceWrappers$0(TelephonyFrameworkInitializer.java:68)
	at android.app.SystemServiceRegistry$121.createService(SystemServiceRegistry.java:1630)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1702)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1382)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1918)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowContextImpl$_ContextImpl_$$Reflector4.getSystemService(Unknown Source)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:88)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:803)
```

https://github.com/robolectric/robolectric/blob/4091c1ce382ad1a829f485045908d9f367e9e55d/sandbox/src/main/java/org/robolectric/internal/bytecode/ShadowWrangler.java#L323 
Class#getDeclaredMethod will causes the class in the return value and parameter to be loaded
```
java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06, mixed mode)
```
```
// use -XX:+TraceClassLoading
// Main.java
public class Main {
    public static void main(String[] args) throws Exception{
        ShadowTelephonyManager.class.getDeclaredMethod("init");
    }
}
// Param.java
public class Param {
}
// ReturnValue.java
public class ReturnValue {
}

// ShadowTelephonyManager.java
public class ShadowTelephonyManager {

    public ReturnValue method(Param param) { return null;}

    public void init() {}
}
```
```
[0.050s][info   ][class,load] ShadowTelephonyManager source: ...
[0.050s][info   ][class,load] Param source: ...
[0.050s][info   ][class,load] ReturnValue source: ...
```

### CODE REVIEW

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java [hunk 1]
```diff
@@ -225,25 +224,25 @@ public int getEventFlags() {
   }
 
   @Implementation(minSdk = S)
-  public void registerTelephonyCallback(Executor executor, TelephonyCallback callback) {
+  public void registerTelephonyCallback(/*Executor*/ Object executor, /*TelephonyCallback*/ Object callback) {
```
Comment (utzcoz) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java:227]: Could you do a type checking in `registerTelephonyCallback` with `Preconditions.checkArgument` + `instanceof`? `ShadowAppOpsManager#noteProxyOpNoThrow` has an example to use it.

Comment (styluo) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java]: Sure, please review again

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java [hunk 2]
```diff
@@ -225,25 +226,30 @@ public int getEventFlags() {
...
     initTelephonyCallback(callback);
     telephonyCallbackRegistrations.add(callback);
   }
 
   @Implementation(minSdk = TIRAMISU)
   protected void registerTelephonyCallback(
-      int includeLocationData, Executor executor, TelephonyCallback callback) {
+      /*int*/ Object includeLocationData, /*Executor*/
+      Object executor, /*TelephonyCallback*/
+      Object callback) {
```
Comment (utzcoz) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java:242]: This method might needs a type checking for `int` too.

Comment (utzcoz) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java:242]: FYI, could you squash commits to one? Thanks.

Comment (styluo) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java:242]: done, please review again

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java [hunk 3]
```diff
@@ -701,7 +708,7 @@ protected void initListener(PhoneStateListener listener, int flags) {
   }
 
   @CallSuper
-  protected void initTelephonyCallback(TelephonyCallback callback) {
+  protected void initTelephonyCallback(Object callback) {
```
Comment (utzcoz) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java:711]: Oh, it might also needs a type checking. I think it is the last needed changes from my perspective.

Comment (styluo) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java:711]: initTelephonyCallback is protected and only called by registerTelephonyCallback, I think type checking is not necessary in this method

Comment (utzcoz) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowTelephonyManager.java:711]: Okay, it's fine.

**Review by utzcoz — APPROVED** [review]
LGTM. Thanks.
