### PR TITLE
Fix perf issue and memory leak in ShadowParcel.

### LINKED ISSUE #2681: Possible memory leak in ShadowParcel
### Description

ShadowParcel will use pointer value 0 as the first ByteBuffer index, but the Parcel class will not invoke nativeDestroy if its recorded native pointer is 0. I suggest starting on index 1 in ShadowParcel.nativeCreate
### Robolectric & Android Version

Robolectric version 3.0

### PR DESCRIPTION
**Pull request by xian**
Fixes #2681.

### CODE REVIEW

File: robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowParcel.java [hunk 1]
```diff
@@ -253,15 +254,10 @@ public static String nativeReadString(long nativePtr) {
...
-    // todo: yikes, perf:
-    // Pick a native ptr that hasn't been used.
-    long/*ptr*/ nativePtrUsed = 0;
-    while (NATIVE_PTR_TO_PARCEL.containsKey(nativePtrUsed)) {
-      nativePtrUsed++;
-    }
-    NATIVE_PTR_TO_PARCEL.put(nativePtrUsed, new ByteBuffer());
-    return castNativePtr(nativePtrUsed);
+  synchronized public static Number nativeCreate() {
+    long nativePtr = nextNativePtr++;
```
Comment (menny) [inline robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowParcel.java]: why do you need `nativePtr`? Is it used anywhere?

Comment (menny) [inline robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowParcel.java]: oh, I see that you initialized `nextNativePtr` with `1`. Did you mean to use `nativePtr` in the `NATIVE_PTR_TO_PARCEL` and `castNativePtr(nextNativePtr);`?

Comment (xian) [inline robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowParcel.java]: Oops, thanks @menny, totally right. Fixed!
