### PR TITLE
fix for NPE when ShadowLegacyAssetManager is used

### LINKED ISSUE #6916: Legacy resource mode NPE w/ Robolectric 4.7.3
### Description
We ran into this because we're using the android-all jar and Robolectric tests in a JVM-only module (no Android stuff) so we can't do "includeAndroidResources" to kick it into binary resources mode.
Trying to do this causes no resources to be found:
systemProperty("robolectric.resourcesMode", "binary")

### Steps to Reproduce
Run test in repro project.

One of our folks worked around this by replacing uses of the resourceTable field with calls to the getResourceTable() method in the shadow asset manager class.

### Robolectric & Android Version
4.7.3.

### Link to a public git repo demonstrating the problem:
see attached repro project
[robolectricLegacyResourcesBug.zip](https://github.com/robolectric/robolectric/files/7669544/robolectricLegacyResourcesBug.zip)

### PR DESCRIPTION
**Pull request by kenyee**
Legacy resources is deprecated, but Robolectric does use this class if you try running Robolectric tests in a JVM only Gradle module.

### Overview
More details in issue #6916

### Proposed Changes
Replace using resourceTable with getResourceTable()

Close #6916 if merged

### CODE REVIEW

**Comment by kenyee** [comment]
FYI, ran " ./gradlew clean assemble testClasses --parallel" on my PR successfully.
Had to run:
git submodule update --init
brew install cmake ninja
as well.

**Comment by utzcoz** [comment]
@kenyee there are some Java format problem. You can follow https://github.com/robolectric/robolectric/wiki/Running-google-java-format to fix this problems locally, and push it.

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java [hunk 1]
```diff
@@ -235,29 +235,24 @@ private void convertAndFill(AttributeResource attribute, TypedValue outValue, Re
 
 
   public TypedResource getAttrTypeData(ResName resName) {
-    return resourceTable.getValue(resName, config);
+    return getResourceTable().getValue(resName, config);
   }
 
   @Implementation
   protected void __constructor__() {
-    resourceTable = RuntimeEnvironment.getAppResourceTable();
```
Comment (utzcoz) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:243]: Is there any reason to delay initialization of `resourceTable`? If not, what about storing `isSystem`, and changing this `resourceTable = *` to `resourceTable = isSystem ? RuntimeEnvironment.getSystemResourceTable() : RuntimeEnvinronment.getAppResourceTable()` only?

Comment (kenyee) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:243]: AFAIK, it's necessary because of the 2nd constructor below that takes isSystem as a parm...

**Comment by kenyee** [comment]
> @kenyee there are some Java format problems. You can follow https://github.com/robolectric/robolectric/wiki/Running-google-java-format to fix this problems locally, and push it.

Yep..fixed...thx :-)

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java (hunk 1 above)
Comment (utzcoz) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:243]: Looks like the second constructor is called, and its calling-chain calls the first constructor, so that the `resourceTable` is rewritten to app resource table.

Comment (utzcoz) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:243]: At least, my tests tell me that my assumption is not correct.

Comment (utzcoz) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:243]: Current tests show that when initializing system `ShadowLegacyAssetManager`, the `RuntimeEnvironment.getSystemResourceTable()` is null.

**Comment by utzcoz** [comment]
> java.lang.Exception
	at org.robolectric.shadows.ShadowLegacyAssetManager.__constructor__(ShadowLegacyAssetManager.java:260)
	at android.content.res.AssetManager.<init>(AssetManager.java)
	at android.content.res.AssetManager.$$robo$$android_content_res_AssetManager$ensureSystemAssets(AssetManager.java:102)
	at android.content.res.AssetManager.ensureSystemAssets(AssetManager.java)
	at android.content.res.AssetManager.$$robo$$android_content_res_AssetManager$getSystem(AssetManager.java:126)
	at android.content.res.AssetManager.getSystem(AssetManager.java)
	at org.robolectric.shadows.ShadowResources.getSystem(ShadowResources.java:78)
	at android.content.res.Resources.getSystem(Resources.java)
	at android.app.ContextImpl.$$robo$$android_app_ContextImpl$createSystemContext(ContextImpl.java:1536)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.robolectric.shadows.ShadowContextImpl$_ContextImpl_$$Reflector4.createSystemContext(Unknown Source)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:251)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)

From the stack trace, `AndroidTestEnvironment.installAndCreateApplication` create system context firstly, and `createSystemContext`'s call-chain initialize system `ShadowLegacyAssetManager`. Because `RuntimeEnvironment#systemResourceTable` is not initialized, so it uses null to initialize `resourceTable`. The `AndroidTestEnvironment.loadAppPackage` that initializes `RuntimeEnvironment#systemResourceTable` is called by `AndroidTestEnvironment.installAndCreateApplication` after `createSystemContext`. So there is a NPE problem when retrieving system resources.

**Review by utzcoz — APPROVED** [review]
Deferring to initialize `resourceTable` LGTM. It's better if we can re-initialize `resourceTable` for system `ShadowLegacyAssetManager`.

**Comment by utzcoz** [comment]
Maybe this caused by frameworks logic changed, but I don't find the real change to cause it.

**Comment by utzcoz** [comment]
> More details in issue #6916

Could you add "Close https://github.com/robolectric/robolectric/issues/6916" to line your issue lifecycle with this PR?

**Comment by utzcoz** [comment]
> > More details in issue #6916
> 
> Could you add "Close #6916" to line your issue lifecycle with this PR?

And could you help to squash to one commit?

**Comment by kenyee** [comment]
> Could you add "Close #6916" to line your issue lifecycle with this PR?

First time contributor, so not sure what you mean by this? 😄

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java [hunk 2]
```diff
@@ -277,7 +272,9 @@ protected void init(boolean isSystem) {
   }
 
   protected ResourceTable getResourceTable() {
-    return resourceTable;
+    return isSystem
```
Comment (hoisie) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:275]: Out of curiosity, why does lazily loading the resource table fix this issue? Why are the resource tables not available in the constructor?

**Review by hoisie — COMMENTED** [review]
Thanks for taking a look and for sending a PR! I'll run this against some tests internally at Google to catch any potential issues.

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java (hunk 2 above)
Comment (kenyee) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:275]: Not entirely sure why lazy loading fixes this issue..

Comment (utzcoz) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:275]: https://github.com/robolectric/robolectric/pull/6918#issuecomment-989047499 https://github.com/robolectric/robolectric/pull/6918#pullrequestreview-826767998  https://github.com/robolectric/robolectric/pull/6918#issuecomment-989053673 @hoisie those comments maybe provide some explanation.

Comment (hoisie) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowLegacyAssetManager.java:275]: This could have been potentially caused by the refactoring of [AndroidTestEnvronment](https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/android/internal/AndroidTestEnvironment.java) to support `@LazyApplication`. I'm find with this solution for now, maybe at some point we can reorder some of the logic in AndroiddTestEnvironment to potentially fix the root cause.

**Comment by hoisie** [comment]
Thank you very much @kenyee for the report and the fix.

**Comment by hoisie** [comment]
@kenyee do you need this in a release? I'd be OK with having this be in a 4.7.4 release.

**Comment by kenyee** [comment]
> @kenyee do you need this in a release? I'd be OK with having this be in a 4.7.4 release.

Whenever your next release is fine...we have a workaround in place for now thanks to @cesar1000  :-)

**Comment by carlonzo** [comment]
@kenyee do you have any suggested workaround for this until 4.7.4 is released?

**Comment by hoisie** [comment]
I can do a 4.7.4 release with this.

One possible workaround is to use a custom ShadowLegacyAssetManager that has the fix.

**Comment by kenyee** [comment]
@carlonzo the custom ShadowLegacyAssetManager is what we do

**Comment by carlonzo** [comment]
Thanks for the help. I actually managed to solve the issue. No need to make a release
