### PR TITLE
Fix tests failing for ShadowDateUtils since the beginning of 2016

### LINKED ISSUE #2194: ShadowDateUtilsTest failing since 2016
On KitKat and above, Android is formatting dates in the form "1/1" instead of "1/1/2016" for example, but only for the current year. For past years, the format is always "1/1/2015".
This appears to happen in DateIntervalFormat.toSkeleton() where the date format is constructed.

This means that when we're expecting "1/1" in the test, we're instead getting "1/1/2015" because we're using Jan 1st, 2015 as the date.

### PR DESCRIPTION
**Pull request by flyingtoaster0**
On KitKat and above, Android is formatting dates in the form "1/1" instead of "1/1/2016" for example, but only for the current year. For past years, the format is always "1/1/2015".
This appears to happen in DateIntervalFormat.toSkeleton() where the date format is constructed.

Fixes #2194

### CODE REVIEW

File: robolectric/src/test/java/org/robolectric/shadows/ShadowDateUtilsTest.java [hunk 1]
```diff
@@ -26,10 +32,24 @@ public void formatDateTime_worksSinceKitKat() {
...
+  }
+
+  @Test
+  @Config(sdk = {
+      Build.VERSION_CODES.JELLY_BEAN,
+      Build.VERSION_CODES.JELLY_BEAN_MR1,
+      Build.VERSION_CODES.JELLY_BEAN_MR2,
+      Build.VERSION_CODES.KITKAT,
+      Build.VERSION_CODES.LOLLIPOP })
+  public void formatDateTime_withPastYear_works() {
```
Comment (jongerrish) [inline robolectric/src/test/java/org/robolectric/shadows/ShadowDateUtilsTest.java]: I think you can drop the "_works" its kind of redundant.

**Comment by jongerrish** [comment]
Just one nit... did you confirm this is the correct behavior on real Android?

**Comment by flyingtoaster0** [comment]
I've not yet tried on a real device, but I'll check it out and see what happens and log an issue if Robolectric and real devices don't have the same behaviour.

**Comment by jongerrish** [comment]
OK, cool.

Let's check the real Android behavior then pre/post Kit Kat before making
changes to the tests. The date formatting is one area of Robolectric that
I'm not super confident in so it would be nice to have a test that enforces
real Android behaviour.

**Comment by jongerrish** [comment]
This is the extend of real androids tests in this area, not great.

https://github.com/android/platform_frameworks_base/blob/7de7e0b0dd61acba813dec3a07d29f1d62026470/core/tests/coretests/src/android/text/format/DateUtilsTest.java

**Comment by flyingtoaster0** [comment]
I tested a handful of devices and here were the results:

**S3 running Jellybean:**
1/01/2016
1/01/2015

**S3 running KitKat:**
1/1
1/1/2015

**Nexus 6 running Marshmallow:**
1-1
1-1-2015

**Nexus 5x running Marshmallow:**
1/1
1/1/2015


So it does indeed seem like since KitKat, the year is being omitted, despite the fact that the Nexus 6 used dashes instead of slashes. It's also a little odd that the S3 running Jellybean had leading 0s, although I could imagine this is could vary in Samsung Android builds.

**Comment by jongerrish** [comment]
Yeah, and maybe the locales?

Feels like your tests are making the correct assertions though right?

**Comment by flyingtoaster0** [comment]
Yeah locales could affect it too. In any case though, yeah, I feel like for what was being tested before, this is a suitable update.

**Comment by jongerrish** [comment]
Thanks for the contribution!
