### PR TITLE
Fixed PFD testGetFd_canRead test failed on macOS.

### LINKED ISSUE #7130: ShadowParcelFileDescriptorTest failed on macOS
### Description

Run `./gradlew :robolectric:test --tests "ShadowParcelFileDescriptorTest"` on macOS(although I run it on macOS with M1, but I don't think it is arch related) and get following failed tests:

```
org.robolectric.shadows.ShadowParcelFileDescriptorTest > testGetFd_canRead[16] FAILED
    java.io.FileNotFoundException: /proc/self/fd/722 (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.robolectric.shadows.ShadowParcelFileDescriptorTest.testGetFd_canRead(ShadowParcelFileDescriptorTest.java:264)
```

Not only SDK 16, but also other SDKs, and above failed log is an example.

### Steps to Reproduce

`./gradlew :robolectric:test --tests "ShadowParcelFileDescriptorTest"` 

### Robolectric & Android Version

Robolectric master branch.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

### PR DESCRIPTION
**Pull request by ZSmallX**
### Overview

Fixed PFD testGetFd_canRead test failed on macOS.  
Avoid depending on Linux file system details, and make full use of Java cross platform feature.

### Proposed Changes

Used `new FileInputStream(FileDescriptor)` instead of `new FileInputStream(String)`.

Note that it can still run failed on Windows.

Closes #7130

### CODE REVIEW

File: robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java [hunk 1]
```diff
@@ -255,13 +255,15 @@ public void testCreatePipeTwice() throws IOException {
...
   public void testGetFd_canRead() throws IOException {
-    assumeThat("Windows is an affront to decency.",
-        File.separator, Matchers.equalTo("/"));
-
     pfd = ParcelFileDescriptor.open(readOnlyFile, ParcelFileDescriptor.MODE_READ_ONLY);
     int fd = pfd.getFd();
     assertThat(fd).isGreaterThan(0);
-    FileInputStream is = new FileInputStream(new File("/proc/self/fd/" + fd));
+
+    final FileDescriptor fD = pfd.getFileDescriptor();
```
Comment (utzcoz) [inline robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java:262]: nit: fD -> fileDescriptor? I know there is a parameter called `fd`.

**Comment by ZSmallX** [comment]
There is no tests run on macOS on GitHub Action, maybe it should be added later.

Tests passed on my macOS.

@utzcoz @hoisie Could you please review on this?

File: robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java [hunk 2]
```diff
@@ -255,13 +255,15 @@ public void testCreatePipeTwice() throws IOException {
 
   @Test
   public void testGetFd_canRead() throws IOException {
-    assumeThat("Windows is an affront to decency.",
```
Comment (utzcoz) [inline robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java:258]: Maybe we should keep this `assumeThat` to ensure this test will not run on Windows. I think this mechanism will not work on Windows.

Comment (utzcoz) [reply robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java:258]: And this PR is used to fix failed test on macOS, not including Windows.

Comment (hoisie) [reply robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java:258]: I can try it real quick on Windows

Comment (ZSmallX) [reply robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java:258]: > And this PR is used to fix failed test on macOS, not including Windows.

@utzcoz I meant to fix it for all platforms. I believe that Java & JVM can do this, but it should be verified.

**Comment by utzcoz** [comment]
I have tested it on my macOS with M1, and the test passed.

File: robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java (hunk 2 above)
Comment (hoisie) [reply robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java:258]: Hmm, on Windows it has an error, and the error is:
```
org.robolectric.shadows.ShadowParcelFileDescriptorTest > testGetFd_canRead[29] FAILED
    expected to be greater than: 0
    but was                    : -1
        at org.robolectric.shadows.ShadowParcelFileDescriptorTest.testGetFd_canRead(ShadowParcelFileDescriptorTest.java:260)
```

Comment (utzcoz) [reply robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java:258]: @hoisie @ZSmallX We can keep this test skipped on Windows, and fix it on macOS firstly with this PR.

Comment (ZSmallX) [reply robolectric/src/test/java/org/robolectric/shadows/ShadowParcelFileDescriptorTest.java:258]: Thanks @hoisie! OK, @utzcoz I will revert the assertion on Windows platform and keep the rest of changes.

**Review by utzcoz — APPROVED** [review]
LGTM. Thanks.

**Comment by hoisie** [comment]
Thanks @ZSmallX !
