### PR TITLE
Reset shadows before resetting package manager

### LINKED ISSUE #1754: SQLiteOpenHelperTest causing FileSystemException on Windows
`SQLiteOpenHelperTest` has never run well on Windows, however with a recent change on master, (looks like attempted cleanup code to remove the temp directory) - I have been running into the following:

      Caused by: java.nio.file.FileSystemException:
      C:\Users\Jeremy\AppData\Local\Temp\android-tmp-robolectric250258741663565975\databases\path:
      The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1123)
        at org.robolectric.util.TempDirectory$2.visitFile(TempDirectory.java:84)
        at org.robolectric.util.TempDirectory$2.visitFile(TempDirectory.java:81)
        at java.nio.file.Files.walkFileTree(Files.java:2667)
        at java.nio.file.Files.walkFileTree(Files.java:2739)
        at org.robolectric.util.TempDirectory.clearDirectory(TempDirectory.java:81)
        at org.robolectric.util.TempDirectory.destroyImpl(TempDirectory.java:70)
        ... 27 more

What seems to happen is that the tests run fine until it gets to the `SQLiteOpenHelperTest`, and thereafter all the tests fail with the above error. The SQLite stuff has never played nice under Windows - Windows is a a little bit more pedantic about removing files that are still in use, and I've always had errors about a process still having the database open in the SQLite-related tests. As I haven't been doing any testing with SQLite so far I've just been ignoring these errors, but now that it's causing other unrelated tests to fail too it gets a bit harder to ignore it.

I'm wondering if this is related to #1510 - if a static reference is held to the connection that persists between tests, then that would hold the file open (and locked) across tests, which would cause the above.

### PR DESCRIPTION
**Pull request by kriegfrj**
This PR lays some groundwork for #1754.

I implemented a fix for #1510 and found that this didn't fix #1754 as I expected. Upon closer inspection, I discovered that the `RobolectricPackageManager.reset()` (which is ultimately what tries to clean up the temp directory for the DBs) was being called *before* the shadows were reset - so my DB cleanup in the shadow connection resetter came too late to fix the problem.

This PR solves this issue by ensuring that the package manager is not reset until after all of the shadows have been reset.

While I was at it I also converted the tests in `RobolectricTestRunnerSelfTest` to use AssertJ rather than plain JUnit assertions.

### CODE REVIEW

File: robolectric/src/main/java/org/robolectric/internal/ParallelUniverse.java [hunk 1]
```diff
@@ -142,13 +143,6 @@ public void setUpApplicationState(Method method, TestLifecycle testLifecycle, Re
 
   @Override
   public void tearDownApplication() {
-    // We would like to null this out (which would call reset) but that can kill async threads
-    // that run after a test complete (because they might call Context.getApplicationInfo()).
-    RobolectricPackageManager rpm = RuntimeEnvironment.getRobolectricPackageManager();
-    if (rpm != null) {
-      rpm.reset();
```
Comment (lexs) [inline robolectric/src/main/java/org/robolectric/internal/ParallelUniverse.java]: Why remote this?

File: robolectric/src/main/java/org/robolectric/Robolectric.java [hunk 2]
```diff
@@ -15,19 +15,18 @@
 
 public class Robolectric {
   private static final ShadowsAdapter shadowsAdapter = instantiateShadowsAdapter();
-  private static ServiceLoader<ShadowProvider> providers;
+  private static Iterable<ShadowProvider> providers;
```
Comment (lexs) [inline robolectric/src/main/java/org/robolectric/Robolectric.java]: Why change this?

Comment (kriegfrj) [inline robolectric/src/main/java/org/robolectric/Robolectric.java]: I couldn't figure out another way to test it because ServiceLoader is final and can't be mocked by Mockito. If you've got another suggestion I'm open to it.

File: robolectric/src/main/java/org/robolectric/internal/ParallelUniverse.java (hunk 1 above)
Comment (kriegfrj) [inline robolectric/src/main/java/org/robolectric/internal/ParallelUniverse.java]: For two reasons: 
1. It was being called twice - once here and again from resetStaticState() (Robolectric.reset() -,> RuntimeEnvironment.setRobobolectricPackageManager(). Didn't see the need to call it twice.
2. As noted, the whole point of this PR is to make that reset call after the shadows are reset. because resetStaticState() comes after tearDownApplication() so i removed the reset call there.

If you've got better ideas I'm open! :smile:
