### PR TITLE
Fix a memory leak in DeviceConfig (#5530)

### LINKED ISSUE #5530: Memory Leak In CppAssetManager2
### Description
I am trying to iterate a test case 1000+ times, the memory is being consumed gradually every time a new instance of **ActivityScenario** is created.

Heap dump:
Untitled
Untitled1
Untitled2

The issue class is CppAssetManager2, it's noticeable that the Theme-related objects are retained regardless of the activity state.
### Steps to Reproduce
```
        ActivityScenario<Activity> scenario;
        for(int i = 0; i < n; i++) {
            scenario = ActivityScenario.launch(intent);
            scenario.onActivity(new ActivityScenario.ActivityAction<Activity>() {
                @Override
                public void perform(Activity activity) {
                    test(activity);
                    activity.finish();
                    scenario.close();
                }
            });
        }
```
### Tried:
```
unitTests.all {
    jvmArgs '-Xmx512m'
}
```

### Robolectric & Android Version
Robolectric 4.3
Android 28

Thanks for your time.

### PR DESCRIPTION
**Pull request by realdadfish**
Reset internal propertyChangedListener in DeviceConfig, as proposed by @hoisie. Fixes #5530.

### CODE REVIEW

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowDeviceConfig.java [hunk 1]
```diff
@@ -13,4 +16,20 @@ protected static String getProperty(String namespace, String name) {
...
+    Object lock = ReflectionHelpers.getStaticField(DeviceConfig.class, "sLock");
+    //noinspection SynchronizationOnLocalVariableOrMethodParameter
+    synchronized (lock) {
+      Map singleListeners = ReflectionHelpers.getStaticField(DeviceConfig.class, "sSingleListeners");
+      singleListeners.clear();
+
+      Map listeners = ReflectionHelpers.getStaticField(DeviceConfig.class, "sListeners");
+      listeners.clear();
+
+      Map namespaces = ReflectionHelpers.getStaticField(DeviceConfig.class, "sNamespaces");
```
Comment (hoisie) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowDeviceConfig.java:31]: I don't think sNamespaces is safe to clear. Internally, when I do this, most Robolectric tests fail with the error:

```
this method should only be called by Robolectric
java.lang.IllegalStateException: 
	at org.robolectric.shadows.ShadowDisplayManager.configureDefaultDisplay(ShadowDisplayManager.java:69)
	at org.robolectric.android.Bootstrap.setUpDisplay(Bootstrap.java:18)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:219)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Weird how that doesn't happen in CircleCI. 

However, if sNamespaces is not cleared, everything seems to work.

Comment (hoisie) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowDeviceConfig.java:31]: Actually, the real error message was:

```
java.lang.RuntimeException: java.lang.NoSuchFieldException: sSingleListeners
	at org.robolectric.util.ReflectionHelpers.getStaticField(ReflectionHelpers.java:200)
	at org.robolectric.shadows.ShadowDeviceConfig.reset(ShadowDeviceConfig.java:26)
	at org.robolectric.Shadows.reset(Shadows.java:2341)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:518)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:349)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:347)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:272)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchFieldException: sSingleListeners
	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
	at org.robolectric.util.ReflectionHelpers.getStaticField(ReflectionHelpers.java:198)
	... 12 more
```

sSingleListeners is only available in API 29, so that should only be cleared with API 29. I think sNamespaces is fine to clear.

**Comment by hoisie** [comment]
Also google-java-format: https://github.com/robolectric/robolectric/wiki/Running-google-java-format. I really need to make this a gradle task...

**Comment by realdadfish** [comment]
Ok, will do all of that. Completely unrelated, but is there a reason why Robolectric is still at an ancient old Gradle (5.4.1) and hasn't enabled parallel task execution (`org.gradle.parallel=true`) and / or hasn't enabled `maxParallelForks` by default? Contributors that don't look for the custom `-PmaxParallelForks=...` command line option might be stuck with very slow test execution.

**Comment by realdadfish** [comment]
Also, some tests don't seem to be executable on Mac / Windows, where the Linux `/proc` filesystem is unknown:

```
org.robolectric.shadows.ShadowParcelFileDescriptorTest > testGetFd_canRead FAILED
    java.io.FileNotFoundException: /proc/self/fd/108 (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.robolectric.shadows.ShadowParcelFileDescriptorTest.testGetFd_canRead(ShadowParcelFileDescriptorTest.java:254)
```

It would be good if these tests could be skipped on these platforms, e.g. by using

```
assumeOperatingSystem(OperatingSystem.Linux)
```

I created a small helper for my own tests here:

```kotlin
enum class OperatingSystem { Windows, Mac, Unix, Unknown }

fun assumeOperatingSystem(os: OperatingSystem) {
    assumeOperatingSystem(equalTo(os))
}

fun assumeOperatingSystem(matcher: Matcher<OperatingSystem>) {
    assumeThat("Assuming specific operating system", OS, matcher)
}

private val OS: OperatingSystem by lazy {
    val osName = System.getProperty("os.name").toLowerCase(Locale.ROOT)
    when {
        osName.indexOf("win") >= 0 -> OperatingSystem.Windows
        osName.indexOf("mac") >= 0 -> OperatingSystem.Mac
        osName.indexOf("nix") >= 0 || osName.indexOf("nux") >= 0 -> OperatingSystem.Unix
        else -> OperatingSystem.Unknown
    }
}
```

Feel free to use that.

**Comment by realdadfish** [comment]
It's a bit of a pity that due to the private nature of `DeviceConfig` I cannot really test whether things are cleared. Would you see it as beneficial to "indirectly" add things to `DeviceConfig` from a higher-level API and see if they're cleared afterwards properly? Issue is - I'd have to create `@VisibleForTesting` API because I cannot access `android.provider.DeviceConfig.class` reflectively from the test, can I?

**Comment by hoisie** [comment]
Tests for Robolectric itself compile against the latest framework Jar (not
the stubs Jar), do you have access to public APIs that are annotated with
`@hide` and such. From a Robolectric-project test you can able to access
DeviceConfig, but not the internal private members.

For the test I'd be fine with just calling the resetter to make sure that
it doesn't crash .

**Comment by hoisie** [comment]
No reason at all why we are still using 5.4. I thought I updated to a more
recent Gradle (6.6?) recently. Is that not being used? Sadly I don't use
Robolectric with Gradle much (google uses bazel), so the Gradle scripts
tend to atrophy faster than other parts of the code base. Feel free to send
PRs if you want to update Gradle.

**Comment by realdadfish** [comment]
> No reason at all why we are still using 5.4. I thought I updated to a more recent Gradle (6.6?) recently. Is that not being used? Sadly I don't use Robolectric with Gradle much (google uses bazel), so the Gradle scripts tend to atrophy faster than other parts of the code base. Feel free to send PRs if you want to update Gradle.

master is still at Gradle 5.4.1. Maybe it would be a good idea (from the contributors side of view, again) to sync the two repos and just use one build system? I could obviously update to the latest version, but usually this comes with some deprecations and more work that needs to be done under the hood (for example, I saw that the Gradle scripts still use the old Maven plugin to publish things and not the newer maven-publish plugin). If any of the Gradle buildscript machinery isn't actually used by the project maintainer(s) then I don't see much reason to develop it any further.

I guess it all boils down how the project is governed as a whole. There are not many contributions coming in outside from Google nowadays.

**Comment by hoisie** [comment]
Thanks again for tracking this down!

**Comment by hoisie** [comment]
Whoops, saw that this went into 4.4.x release branch. That's fine, I'll merge it into master as well.

**Comment by realdadfish** [comment]
Yes, sorry, I hoped for a 4.4.1 release. I'm currently playing around with 4.5-alpha-1, but have problems with the artifact fetching for the Android 11 SDK (local issues, our Artifactory instance does not mirror the `*.sha1` files of the sonatype repository and the `MavenArtifactFetcher` depends on validating `*.sha1` and not `*.sha512` files our repo only contains).

**Comment by hoisie** [comment]
On master I thought I updated gradle to 6.6.1: #5992. Is it still not being used?

```
hoisie@hoisie ~/workspace/robolectric (master) $ ./gradlew --version

------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------
```

Yeah I definitely want to switch to the new maven-publish plugin to use sha512 amongst other reasons.

**Comment by realdadfish** [comment]
Sorry, was on an old master version I suppose :)

**Comment by hoisie** [comment]
We can update MavenArtifactFetcher to use sha512. The most recent android-all jars are published with sha512 checksums as well. Seems like a good idea from a security standpoint.

**Comment by realdadfish** [comment]
I could fix my issue, the admins created another proxy repository. Previously, we used https://oss.sonatype.org/content/groups/public/, but this was missing the SHA-1 checksums, now we use 
https://oss.sonatype.org/service/local/repositories/releases/content and this seems to work. Thanks again!
