### PR TITLE
Changed ShadowAssetManager.APPLIED_STYLES to make it non-static

### LINKED ISSUE #1795: ShadowResourcesTest intermittent failures
I am seeing the following failures on my machine:

````
Failed tests:
  ShadowResourcesTest.getThemeValueShouldSupportNotDereferencingResource:439 expected:<[1717044]4> but was:<[6656]4>
  ShadowResourcesTest.getThemeValueShouldSupportDereferenceResource:425 expected:<-1677[7216]> but was:<-1677[6961]>
````
A closer inspection of the second one revealed that this is a 4-byte color value which is being right-padded with 0xFF when it should be being right-padded with 0xFF. I haven't looked into the first yet but it looks like a slightly different issue (the hex for the two reported numbers is expecting:  0x0106000C, got 0x00010404). 

The failures are not consistent - sometimes one will fail, sometimes neither, sometimes both. Given that they don't seem to be an issue in Travis, I am suspecting one of two possibilities:

1. They happen only only on Windows.
2. They don't happen on a clean run - only on the second run.

I plan to investigate this but thought I would report the issue in case anyone else has seen this and has something useful to add that could help in tracking it down.

### PR DESCRIPTION
**Pull request by kriegfrj**
Per the title. This ensures the applied styles cache will get cleaned up when the `AssetManager` does. This brings it into line with state variables in other parts of the `AssetManager` and also fixes #1795 (though without an explicit test case, which proved too hard to be worth the effort).

Also fixed some lint (dead code, raw types).

### CODE REVIEW

**Comment by kriegfrj** [comment]
I've seen that failure before but it appears unrelated to the changes in this PR.

File: robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowAssetManager.java.vm [hunk 1]
```diff
@@ -271,19 +268,21 @@ public final class ShadowAssetManager {
...
   @HiddenApi @Implementation
   public static void applyThemeStyle($ptrClass theme, int styleRes, boolean force) {
-    if (!APPLIED_STYLES.containsKey(theme)) {
-      APPLIED_STYLES.put(theme, new LinkedList<OverlayedStyle>());
-    }
-
     ResourceLoader resourceLoader = getInstance().getResourceLoader();
     ShadowAssetManager assetManager = shadowOf(getInstance().getAssets());
 
+	final Map<$ptrClassBoxed, List<OverlayedStyle>> appliedStyles = assetManager.appliedStyles;
```
Comment (jongerrish) [inline robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowAssetManager.java.vm]: Indent

Comment (kriegfrj) [inline robolectric-shadows/shadows-core/src/main/resources/org/robolectric/shadows/ShadowAssetManager.java.vm]: Thanks @jongerrish, my apologies. Another minor disadvantage of having velocity source files - Eclipse treats it as plain text instead of Java source and uses different formatting rules.

**Comment by jongerrish** [comment]
Thanks for the cleanup. I think I made it static originally for performance, but someone re-wrote that code to make it run much faster than my original implementation :-)
