### PR TITLE
Filter out disabled components in PackageManager query/resolve method…

### LINKED ISSUE #3748: 3.7 regression regarding disabling then querying activity components?
### Description
Our app code disables an activity component, then queries the package manager to see if there are any other activities that can handle a given intent.

With robolectric 3.6.1, `queryIntentActivities()` doesn't return our own activity, which is expected, and what we observe on real devices.

With robolectric 3.7, our activity is returned by `queryIntentActivities()`.

```java
PackageManager packageManager = context.getPackageManager();
ComponentName deepLinkReceiverComponent = new ComponentName(context.getApplicationContext(), DeepLinkReceiver.class);
packageManager.setComponentEnabledSetting(deepLinkReceiverComponent, PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);

Intent callIntent = new Intent(Intent.ACTION_DIAL);
callIntent.setData(Uri.parse("tel:" + phoneNumber));
callIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

List<ResolveInfo> resolveInfos = context.getPackageManager().queryIntentActivities(callIntent, 0);
// On 3.6.1, resolveInfos doesn't have our activity. On 3.7, it does.
```
### Android and Robolectric versions
Robolectric 3.7
We target Android 27 in our app and in our robolectric config.

### PR DESCRIPTION
**Pull request by brettchabot**
…s unless MATCH_DISABLED_COMPONENTS is specified.

Fixes #3748

This commit attempts to add this support while retaining backwards compatibilty wrt the quirks of the existing implementation.

### CODE REVIEW

File: robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java [hunk 1]
```diff
@@ -592,6 +592,55 @@ public void queryIntentActivities_MatchWithAliasIntents() throws Exception {
...
+    i.setDataAndType(uri, "image/jpeg");
+
+    ComponentName componentToDisable = new ComponentName(RuntimeEnvironment.application,
+        "org.robolectric.shadows.TestActivity");
+    packageManager.setComponentEnabledSetting(componentToDisable,
+        PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
+
+    List<ResolveInfo> resolveInfos = packageManager.queryIntentActivities(i, 0);
+    assertThat(resolveInfos).isNotNull();
+    assertThat(resolveInfos).hasSize(0);
```
Comment (jongerrish) [inline robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java]: isEmpty() I think you can do rather than hasSize(0)

File: robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java [hunk 2]
```diff
@@ -592,6 +592,55 @@ public void queryIntentActivities_MatchWithAliasIntents() throws Exception {
...
+    i.setClassName(RuntimeEnvironment.application, "org.robolectric.shadows.TestActivity");
+
+    ComponentName componentToDisable = new ComponentName(RuntimeEnvironment.application,
+        "org.robolectric.shadows.TestActivity");
+    packageManager.setComponentEnabledSetting(componentToDisable,
+        PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
+
+    List<ResolveInfo> resolveInfos = packageManager.queryIntentActivities(i, 0);
+    assertThat(resolveInfos).isNotNull();
+    assertThat(resolveInfos).hasSize(0);
```
Comment (jongerrish) [inline robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java]: isEmpty() - probably covers the null case too.

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java [hunk 3]
```diff
@@ -280,22 +280,39 @@ protected PackageInfo getPackageInfo(String packageName, int flags) throws NameN
     // Create a copy of the list for filtering
     resolveInfoList = new ArrayList<>(resolveInfoList);
 
-    if ((flags & PackageManager.MATCH_SYSTEM_ONLY) == PackageManager.MATCH_SYSTEM_ONLY) {
```
Comment (jongerrish) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java]: Might be worth extracting a method here

isFlagSet(int flags, int flag) - your call.

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java [hunk 4]
```diff
@@ -280,22 +280,39 @@ protected PackageInfo getPackageInfo(String packageName, int flags) throws NameN
...
-          if ((applicationFlags & ApplicationInfo.FLAG_SYSTEM) != ApplicationInfo.FLAG_SYSTEM) {
-            iterator.remove();
-          }
         }
       }
     }
     return resolveInfoList;
   }
 
+  private boolean isValidComponentInfo(ComponentInfo componentInfo) {
```
Comment (jongerrish) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java]: can be static

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java (hunk 3 above)
Comment (brettchabot) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java]: done

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java (hunk 4 above)
Comment (brettchabot) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowApplicationPackageManager.java]: done

File: robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java (hunk 2 above)
Comment (brettchabot) [reply robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java]: done

File: robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java (hunk 1 above)
Comment (brettchabot) [reply robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java]: done
