### PR TITLE
Fix Bitmap.getDensity() return invalid value

### LINKED ISSUE #6043: SwitchCompat in a ConstraintLayout in a NestedScrollView has inaccurate height
### Description
SwitchCompat inside a ConstraintLayout inside a NestedScrollView has a height of `height=16777214` which causes operations like `isCompletelyDisplayed()` to fail. This also prevents clicks for a similar reason if you have several switches in the same layout.

### Steps to Reproduce

1. Checkout the git repo reproducing the problem. Specifically the [MainFragmentTest class](https://github.com/mezpahlan/switchcompat-robolectric-bug/blob/master/app/src/test/java/uk/co/mezpahlan/switchcompatrobolectricbug/ui/main/MainFragmentTest.kt) and the [main_fragment layout](https://github.com/mezpahlan/switchcompat-robolectric-bug/blob/master/app/src/main/res/layout/main_fragment.xml)
2. Run the linked test. 

### Expected Result

The test passes and the height is reported at a sensible value.

### Actual Result
The test fails and the height is reported as 16777214
>androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'at least 100 percent of the view's area is displayed to the user.' doesn't match the selected view.
Expected: at least 100 percent of the view's area is displayed to the user.
     Got: "SwitchCompat{id=2131231095, res-name=switch_compat_2, visibility=VISIBLE, width=320, height=16777214, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@54738eaa, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1.6777216E7, text=Don't Switch Me, input-type=0, ime-target=false, has-links=false, is-checked=false}"

Note that if I change the view reference to the top most SwitchCompat the test passes. This also passes if I only have a single item inside the ConstraintLayout.

Also note that in the design editor in Android Studio the SwitchCompat looks normal, as it does when you run the app on a device.

Screenshot from 2020-11-04 23-07-55

### Robolectric & Android Version
Roblectric 4.4
Android 7 - SDK / API 24

### Link to a public git repo demonstrating the problem:
[Minimal project to reproduce a bug with SwitchCompat NestedScrollView and Robolectric](https://github.com/mezpahlan/switchcompat-robolectric-bug)

### PR DESCRIPTION
**Pull request by LitterSun**
Fixes #6043

### CODE REVIEW

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java [hunk 1]
```diff
@@ -231,6 +232,11 @@ public static Bitmap create(final String name, final BitmapFactory.Options optio
       options.outWidth = p.x;
       options.outHeight = p.y;
     }
+
+    if (shadowBitmap.getDensity() <= Bitmap.DENSITY_NONE) {
```
Comment (hoisie) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java:236]: Does this mean that all bitmaps created with BitmapFactory.decodeByteArray will have their density set to DisplayMetrics.DENSITY_DEVICE? Aren't there valid use cases for DENSITY_NONE?

Comment (hoisie) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java:236]: Should this instead check for the density-related fields in `BitmapFactory.Options opts`?

**Comment by hoisie** [comment]
FYI, with this change, there seems to be a problem using `context.getDrawable` with  `@Config(qualifiers = "hdpi")`. You can see this by adding this test to [ResourcesTest](https://github.com/robolectric/robolectric/blob/master/integration_tests/ctesque/src/test/java/android/content/res/ResourcesTest.java)

```java
  @Test
  @Config(qualifiers = "hdpi")
  public void testHdpiScale() throws Exception {
    BitmapDrawable drawable = (BitmapDrawable) context.getDrawable(R.drawable.an_image);
    assertThat(drawable.getIntrinsicWidth()).isEqualTo(64); // with this change, this test fails because drawable.getIntrinsicWidth returns 96
  }
```

**Comment by hoisie** [comment]
Would you be able to extract the bug that this addresses into a unit test in ResourcesTest as well? I am still unclear what the underlying problem in #6043 is and how this addresses it.

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java (hunk 1 above)
Comment (LitterSun) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java]: Thank you for your reply. Your suggestion is right. I rewrote the code and added test. Please review again.

**Comment by LitterSun** [comment]
@hoisie By the way, is there a script that can run all tests locally?

**Comment by LitterSun** [comment]
> Would you be able to add a unit test in [ResourcesTest](https://github.com/robolectric/robolectric/blob/master/integration_tests/ctesque/src/test/java/android/content/res/ResourcesTest.java) as well that captures this issue? I am still unclear what the underlying problem in #6043 is and how this addresses it.

At API 24, NinePatchDrawable#computeBitmapSize method,
```java
...
        final int sourceDensity = ninePatch.getDensity(); // return mBitmap.mDensity, may be 0
        final int targetDensity = mTargetDensity;
...
        mBitmapHeight = Drawable.scaleFromDensity(
                ninePatch.getHeight(), sourceDensity, targetDensity, true); // if sourceDensity=0, return 0x7FFFFFFF
        mBitmapWidth = Drawable.scaleFromDensity(
                ninePatch.getWidth(), sourceDensity, targetDensity, true);
...
```
When API 28
```java
        final int targetDensity = mTargetDensity;
        final int sourceDensity = ninePatch.getDensity() == Bitmap.DENSITY_NONE ?
            targetDensity : ninePatch.getDensity();
```
So this issue will not happen on Android 9.
These are my findings. If there are any mistakes, please point them out.

**Comment by hoisie** [comment]
It would still be great to get a unit test that captures this in a reduced test case. Seems like to capture this, you can try to load a NinePatchDrawable and ensure that the width/height/density are valid? You can also use `@Config(sdk=24)` to run this on API 24.

**Comment by hoisie** [comment]
This seems to be a test that captures it well:
```
  @Test
  @Config(sdk=24)
  public void testGetNinePatchDrawableIntrinsicWidth() {
    assertThat(resources.getDrawable(R.drawable.nine_patch_drawable).getIntrinsicWidth()).isEqualTo(98);
  }
```

Alternatively there a way to modify [ShadowNinePatch](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowNinePatch.java) to fix this? The reason I ask is because the fallback density in NinePatch seems to be device density, so I am wondering why that fallback is not triggered on SDK 24.

**Comment by LitterSun** [comment]
> This seems to be a test that captures it well (also in ResourcesTest):
> 
> ```java
>   @Test
>   @Config(sdk=24)
>   public void testGetNinePatchDrawableIntrinsicWidth() {
>     assertThat(resources.getDrawable(R.drawable.nine_patch_drawable).getIntrinsicWidth()).isEqualTo(98);
>   }
> ```
> 
> Alternatively there a way to modify [ShadowNinePatch](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowNinePatch.java) to fix this? The reason I ask is because the fallback density in NinePatch seems to be device density, so I am wondering why that fallback is not triggered on SDK 24.

This is a good unit test, it is exactly what I want. 
You said because the fallback density in NinePatch seems to be device density, this refers specifically to which code or method. And I didn't find NinePatch making changes to the Bitmap.density.

Alternatively there a way to modify ShadowNinePatch to fix this?
I don't think it's reasonable, for example
I compare `ShadowBitmapFactory#decodeStream(InputStream is, Rect outPadding, BitmapFactory.Options opts)` and `BitmapFactory#decodeStream(InputStream is, Rect outPadding, Options opts)`, I found that ShadowBitmapFactory lacks a call to `setDensityFromOptions`
```
private static void setDensityFromOptions(Bitmap outputBitmap, Options opts) {
        if (outputBitmap == null || opts == null) return;

        final int density = opts.inDensity;
        if (density != 0) {
            outputBitmap.setDensity(density);
            final int targetDensity = opts.inTargetDensity;
            if (targetDensity == 0 || density == targetDensity || density == opts.inScreenDensity) {
                return;
            }

            byte[] np = outputBitmap.getNinePatchChunk();
            final boolean isNinePatch = np != null && NinePatch.isNinePatchChunk(np);
            if (opts.inScaled || isNinePatch) {
                outputBitmap.setDensity(targetDensity);
            }
        } else if (opts.inBitmap != null) {
            // bitmap was reused, ensure density is reset
            outputBitmap.setDensity(Bitmap.getDefaultDensity());
        }
    }
```
So, I think the best solution is to add the call to `setDensityFromOptions`, if you agree with my solution, I can resubmit a PR.

**Comment by hoisie** [comment]
Yes, calling setDensityFromOptions sounds like a great option to me! Better
to use real android code if possible.

Thanks again for looking into this.

**Comment by hoisie** [comment]
Ok I spent a bit of time looking into this and I think you have to do 2 things:
1) Add the call to `setDensityFromOptions` in ShadowBitmapFactory
2) Remove the [setDensity](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmap.java#L545-L548)/[getDensity](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmap.java#L550-L553) `@Implementation` methods in ShadowBitmap. NinePatch on <=N seems to rely on `mDensity` being valid, which does not happen with the shadows: https://cs.android.com/android/platform/superproject/+/android-7.1.1_r58:frameworks/base/graphics/java/android/graphics/NinePatch.java;l=219-221'

**Comment by hoisie** [comment]
Also can you add the tests referenced in https://github.com/robolectric/robolectric/pull/6047#issuecomment-723532343 and  https://github.com/robolectric/robolectric/pull/6047#issuecomment-723358848 to resourcestest?

**Comment by hoisie** [comment]
Also, I renamed the `integration_tests` directories to `integrationtests`, so you'll need to rebase

**Comment by LitterSun** [comment]
> Ok I spent a bit of time looking into this and I think you have to do 2 things:
> 
> 1. Add the call to `setDensityFromOptions` in ShadowBitmapFactory
> 2. Remove the [setDensity](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmap.java#L545-L548)/[getDensity](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmap.java#L550-L553) `@Implementation` methods in ShadowBitmap. NinePatch on <=N seems to rely on `mDensity` being valid, which does not happen with the shadows: https://cs.android.com/android/platform/superproject/+/android-7.1.1_r58:frameworks/base/graphics/java/android/graphics/NinePatch.java;l=219-221'

**Comment by LitterSun** [comment]
OK, I commit it later

**Comment by LitterSun** [comment]
> Also can you add the tests referenced in [#6047 (comment)](https://github.com/robolectric/robolectric/pull/6047#issuecomment-723532343) and [#6047 (comment)](https://github.com/robolectric/robolectric/pull/6047#issuecomment-723358848) to resourcestest?
There are already many test cases in [ShadowDrawableTest](https://github.com/robolectric/robolectric/blob/8a073e6d1d07a56814aebc95f37ce593f45e0ed8/robolectric/src/test/java/org/robolectric/shadows/ShadowDrawableTest.java) , I only added `testGetNinePatchDrawableIntrinsicWidth`

File: integration_tests/androidx_test/src/test/java/org/robolectric/integrationtests/axt/EspressoWithSwitchCompat.java [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+import org.junit.runner.RunWith;
+import org.robolectric.annotation.Config;
+import org.robolectric.annotation.LooperMode;
+import org.robolectric.annotation.TextLayoutMode;
+import org.robolectric.integration.axt.R;
+
+@RunWith(AndroidJUnit4.class)
+@TextLayoutMode(TextLayoutMode.Mode.REALISTIC)
+@LooperMode(PAUSED)
+@Config(sdk = {24})
```
Comment (hoisie) [inline integration_tests/androidx_test/src/test/java/org/robolectric/integrationtests/axt/EspressoWithSwitchCompat.java:22]: Remove this line so it will run on all SDK levels.

File: integration_tests/androidx_test/src/test/java/org/robolectric/integrationtests/axt/EspressoWithSwitchCompat.java [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+import org.junit.Test;
+import org.junit.runner.RunWith;
+import org.robolectric.annotation.Config;
+import org.robolectric.annotation.LooperMode;
+import org.robolectric.annotation.TextLayoutMode;
+import org.robolectric.integration.axt.R;
+
+@RunWith(AndroidJUnit4.class)
+@TextLayoutMode(TextLayoutMode.Mode.REALISTIC)
+@LooperMode(PAUSED)
```
Comment (hoisie) [inline integration_tests/androidx_test/src/test/java/org/robolectric/integrationtests/axt/EspressoWithSwitchCompat.java:21]: Remove this line, it is the default.

File: integration_tests/ctesque/src/test/java/android/content/res/ResourcesTest.java [hunk 4]
```diff
@@ -439,6 +439,12 @@ public void testGetBitmapDrawableForUnknownId() {
     assertThat(resources.getDrawable(Integer.MAX_VALUE)).isInstanceOf(BitmapDrawable.class);
   }
 
+  @Test
```
Comment (hoisie) [inline integration_tests/ctesque/src/test/java/android/content/res/ResourcesTest.java:442]: Can you change this test to take density into account? We run this test on devices as well:

```java
  @Test
  public void testGetNinePatchDrawableIntrinsicWidth() {
    Float density = resources.getDisplayMetrics().density;
    NinePatchDrawable ninePatchDrawable =
        (NinePatchDrawable) resources.getDrawable(R.drawable.nine_patch_drawable);
    assertThat((float) ninePatchDrawable.getIntrinsicWidth()).isEqualTo(98.0f * density);
  }
```

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmap.java [hunk 5]
```diff
@@ -545,6 +545,7 @@ protected int getHeight() {
   @Implementation
```
Comment (hoisie) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmap.java:545]: Can you remove this method (and getDensity below). It is better to use the real implementation if possible. Also remove the `private int density;` member and you may need to fix a couple of times that `density` is set.

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java [hunk 6]
```diff
@@ -231,6 +232,14 @@ public static Bitmap create(final String name, final BitmapFactory.Options optio
...
       options.outHeight = p.y;
     }
+
+    if (options != null && RuntimeEnvironment.getApiLevel() >= Build.VERSION_CODES.KITKAT) {
+      ReflectionHelpers.callStaticMethod(
+          BitmapFactory.class,
+          "setDensityFromOptions",
+          ClassParameter.from(Bitmap.class, bitmap),
+          ClassParameter.from(BitmapFactory.Options.class, options));
+    }
```
Comment (hoisie) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java:242]: I think this should do something for SDK < 19 as well:

```java
    if (RuntimeEnvironment.getApiLevel() >= Build.VERSION_CODES.KITKAT) {
      ReflectionHelpers.callStaticMethod(
          BitmapFactory.class,
          "setDensityFromOptions",
          ClassParameter.from(Bitmap.class, bitmap),
          ClassParameter.from(BitmapFactory.Options.class, options));
    } else if (options != null && options.inDensity != 0) {
      bitmap.setDensity(options.inDensity);
    }
```

Comment (LitterSun) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java:242]: I copy `setDensityFromOptions` from `BitmapFactory`, it makes the logic more complete and makes the code more readable

Comment (hoisie) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java]: We have a pretty strong preference to call the real Android code wherever possible. On Android < 19, the function is named [finishDecode](https://cs.android.com/android/platform/superproject/+/android-4.3.1_r1:frameworks/base/graphics/java/android/graphics/BitmapFactory.java;l=556), but most of that does not seem too relevant except the `bm.setDensity(density);`.

Comment (LitterSun) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java]: Get, I will call the real Android code

**Comment by hoisie** [comment]
When you're done can you also squash the commits? I will then merge after that. Thanks again for investigating this!

**Comment by LitterSun** [comment]
> I don't think we need another public `create` method. Can you just pass `null` for outPadding below and not add a new `create` method?

I just want to change the existing code less. if you don't think we need another public `create` method, I will change.

**Comment by hoisie** [comment]
> > I don't think we need another public `create` method. Can you just pass `null` for outPadding below and not add a new `create` method?
> 
> I just want to change the existing code less. if you don't think we need another public `create` method, I will change.

Yeah, I don't think we need another `create` method, especially because `outPadding` is always null. How is introducing a new create method changing the existing code less?

**Comment by LitterSun** [comment]
> > > I don't think we need another public `create` method. Can you just pass `null` for outPadding below and not add a new `create` method?
> > 
> > 
> > I just want to change the existing code less. if you don't think we need another public `create` method, I will change.
> 
> Yeah, I don't think we need another `create` method, especially because `outPadding` is always null. How is introducing a new create method changing the existing code less?

I'm sorry, it was my mistake, outPadding isn't always null.

File: shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java [hunk 7]
```diff
@@ -185,18 +187,22 @@ protected static Bitmap decodeByteArray(
...
     return create(name, null);
   }
 
   public static Bitmap create(String name, BitmapFactory.Options options) {
-    return create(name, options, null);
+    return create(name, null, options, null);
   }
 
-  public static Bitmap create(final String name, final BitmapFactory.Options options, final Point widthAndHeight) {
+  public static Bitmap create(
```
Comment (hoisie) [inline shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java:201]: If you really want a 4-arg create that is fine, just make it private fo now. I would not prefer not to introduce new public APIs in ShadowBitmapFactory.

Also, can you keep the 3-arg `create(String, final BitmapFactory.Options, Point)`  to avoid breaking exising tests?

Comment (LitterSun) [reply shadows/framework/src/main/java/org/robolectric/shadows/ShadowBitmapFactory.java:201]: OK, that's what I'm looking forward to

**Comment by hoisie** [comment]
Awesome, thanks! Looks great. I'll run this change against some tests internally to check for any other potential issues and will merge it tomorrow morning.
